version: 2

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0
